### ISSUE TITLE
Kästchenraster mit beliebig vielen Zellen anzeigen

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#1]
Zellen in Zeilen- / Spaltenstruktur mit fester Größe innerhalb eines Fensters anzeigen. Zu Beginn eines neuen Spreadsheets soll das Raster eine feste Größe haben (so groß wie das Fenster).

**Comment by luisebenkert** [comment]
Estimate: 8 hours

**Comment by ekrebs5** [comment]
noch nicht abgenomme, Buttons für das hinzufügen und entfernen von Spalten/Zeilen

**Comment by ekrebs5** [comment]
abgenommen
