### ISSUE TITLE
Datentypen implementieren

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#12]
Zellen soll ein bestimmter Datentyp zugewiesen werden können, nach welchem der Zelleninhalt automatisch formatiert wird. Dazu können gehören:

- Zahl (+ Spezifikation von Nachkommastellen)
- Text
- Datum
- Zeit
- Währung
- Prozent
- Bruch
- kein Typ

Die Auswahl soll im Menü stattfinden.

**Comment by jaunruh** [comment]
All flyweights have been extended with a correct regex and a correct formatting function.
