### ISSUE TITLE
Simple Rechenfunktionen innerhalb einer Zelle

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#13]
Innerhalb einer Zelle können simple Rechenfunktionen eingegeben werden (z.B. = 1 + 1). Das Ergebnis dieser Rechnung wird dann in diese Zelle eingetragen. Es muss einen Indikator geben, dass es sich um eine Funktion handelt und nicht nur Text.

**Comment by luisebenkert** [comment]
Estimate: 3 hours

**Comment by Askir** [comment]
ok cool

**Comment by philipphoberg** [comment]
Done.
