### ISSUE TITLE
Zellen die angeklickt wurden, bekommen dauerhaft blauen Rahmen

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#14]
Wenn man in eine Zelle reinklickt oder per Tab reinspringt, egal ob man Text ändert oder nicht, bekommt die Zelle einen blauen Rahmen, der auch bleibt, wenn man in eine andere Zelle klickt. Muss gefixt werden, dass nur die aktive Zelle markiert ist.

**Comment by ekrebs5** [comment]
abgenommen
