### ISSUE TITLE
Funktionen werden gespeichert

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/SWT18-Project-18#17]
Wenn ich eine Zelle mit einer Funktion habe, wird in der Zelle das Ergebnis dargestellt, aber ich kann die Funktion noch editieren, wenn ich die Zelle anklicke.

Für Funktionen und andere Zellen gibt es ein Edit-Fenster/-Zeile.

**Comment by ekrebs5** [comment]
Teil von #5

**Comment by philipphoberg** [comment]
Done.
