### ISSUE TITLE
Größe der Zellen beliebig anpassbar

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#2]
Höhe und Breite der Zellen sind beliebig anpassbar

**Comment by luisebenkert** [comment]
Verschieben durch Ziehen der Linie zwischen zwei Zeilen/Spalten, sodass alle Zellen dieser Einheit kleiner bzw. größer werden.

**Comment by ekrebs5** [comment]
abgenommen
