### ISSUE TITLE
Remove Button muss ausgegraut werden

### ISSUE THREAD

**Issue by philipphoberg** [hpi-swa-teaching/SWT18-Project-18#36]
Weiterer Klick auf Remove Button bei 0 Reihen / 0 Zeilen führt zu Crash

**Comment by luisebenkert** [comment]
Button wird nicht direkt ausgegraut aber sobald nur noch eine Spalte oder Zeile vorhanden sind, kann keine weitere entfernt werden.

**Comment by ekrebs5** [comment]
nicht ausgegraut, sondern letzte Zeile/Spalte nicht gelöscht
