### ISSUE TITLE
Erweiterbares Menü anzeigen - Speichern, laden, neu

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#4]
Im Spreadsheet Fenster soll eine Menüleiste eingebunden werden, welches beliebig erweiterbar ist. Zunächst soll es nur die Standard Aktionen (Speichern, Öffnen, Neu) umsetzen. Zusätzliche Funktionen können später noch hinzugefügt werden.

**Comment by luisebenkert** [comment]
genaue Menüpunkte müssen später noch festgelegt werden

**Comment by ekrebs5** [comment]
- [ ] ston
- [ ] csv

**Comment by ekrebs5** [comment]
2 Spalten markieren und Button klicken -> erstellt Chart

**Comment by ekrebs5** [comment]
muss noch auf Master gemerged werden

**Comment by ekrebs5** [comment]
abgenommen
