### ISSUE TITLE
Komplexe Funktionen zwischen Zellen

### ISSUE THREAD

**Issue by luisebenkert** [hpi-swa-teaching/SWT18-Project-18#6]
Komplexe Funktionen (Min, Max, Durchschnitt) können auf den Inhalt beliebig vieler Zellen angewandt werden. Das Ergebnis wird in eine neue Zelle eingetragen. Zusätzliche Funktionen können später noch hinzugefügt werden.

**Comment by luisebenkert** [comment]
Min, Max, Durchschnitt, Summe, Produkt

**Comment by ekrebs5** [comment]
min max durchschnitt fehlen noch

**Comment by ekrebs5** [comment]
abgenommen
