### ISSUE TITLE
Keine Morphs für Zellen

### ISSUE THREAD

**Issue by Adrian-St** [hpi-swa-teaching/SWT18-Project-18#62]
Im Moment wird für jede Zelle eine PHLabel Morph erstellt.
Das verursacht wahrscheinlich die performance Probleme.
Eine mögliche Lösung wäre die Zellen über drawOn: zu zeichnen und die Zellen nur als Objekte zu speichern.

**Comment by ekrebs5** [comment]
abgenommen
